[package]
name = "nu_plugin_prometheus"
description = "A nushell plugin for querying prometheus"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
nu-plugin = "0.94.0"
nu-protocol = { version = "0.94.0", features = [ "plugin" ] }
prometheus-http-query = "0.8.3"
reqwest = { version = "0.12.4", features = [ "native-tls" ] }
tokio = { version ="1.37.0", features = [ "macros", "rt" ] }

[dev-dependencies]
rstest = { version = "0.21", default-features = false }
serde = "1.0.203"
serde_json = "1.0.117"
